# designer_1773810119832.py
# Generated by Designer Agent
# Task: 设计简约风格的网页计算器界面，包含显示屏、按键区域和历史记录面板
# Created: 2026-03-18T05:01:59.832Z

design_spec = {
    "project": "设计简约风格的网页计算器界面，包含显示屏、按键区域和历史记录面板",
    "created": "2026-03-18T05:01:59.832Z",
    "colors": {
        "primary": "#FF6B3D",
        "secondary": "#FF8F6B",
        "background": "#F8F9FA",
        "text": "#1A1A2E"
    },
    "typography": {
        "font_family": "Inter, sans-serif",
        "sizes": {
            "h1": "24px",
            "h2": "18px",
            "body": "14px",
            "small": "12px"
        }
    },
    "components": [
        {
            "name": "Header",
            "description": "Main navigation header"
        },
        {
            "name": "Card",
            "description": "Content card component"
        }
    ]
}

# Design tokens
tokens = {
    "spacing": [4, 8, 12, 16, 24, 32],
    "borderRadius": [4, 8, 12, 16, 24],
    "shadows": ["sm", "md", "lg"]
}
