# designer_1773805267458.py
# Generated by Designer Agent
# Task: 设计待办事项应用界面，包含任务列表、优先级标识（高/中/低）、分类标签、操作按钮等组件的布局和交互
# Created: 2026-03-18T03:41:07.459Z

design_spec = {
    "project": "设计待办事项应用界面，包含任务列表、优先级标识（高/中/低）、分类标签、操作按钮等组件的布局和交互",
    "created": "2026-03-18T03:41:07.459Z",
    "colors": {
        "primary": "#FF6B3D",
        "secondary": "#FF8F6B",
        "background": "#F8F9FA",
        "text": "#1A1A2E"
    },
    "typography": {
        "font_family": "Inter, sans-serif",
        "sizes": {
            "h1": "24px",
            "h2": "18px",
            "body": "14px",
            "small": "12px"
        }
    },
    "components": [
        {
            "name": "Header",
            "description": "Main navigation header"
        },
        {
            "name": "Card",
            "description": "Content card component"
        }
    ]
}

# Design tokens
tokens = {
    "spacing": [4, 8, 12, 16, 24, 32],
    "borderRadius": [4, 8, 12, 16, 24],
    "shadows": ["sm", "md", "lg"]
}
