# designer_1773805537303.py
# Generated by Designer Agent
# Task: 设计网页UI原型，包括持仓管理页面、分析仪表盘、图表布局
# Created: 2026-03-18T03:45:37.303Z

design_spec = {
    "project": "设计网页UI原型，包括持仓管理页面、分析仪表盘、图表布局",
    "created": "2026-03-18T03:45:37.303Z",
    "colors": {
        "primary": "#FF6B3D",
        "secondary": "#FF8F6B",
        "background": "#F8F9FA",
        "text": "#1A1A2E"
    },
    "typography": {
        "font_family": "Inter, sans-serif",
        "sizes": {
            "h1": "24px",
            "h2": "18px",
            "body": "14px",
            "small": "12px"
        }
    },
    "components": [
        {
            "name": "Header",
            "description": "Main navigation header"
        },
        {
            "name": "Card",
            "description": "Content card component"
        }
    ]
}

# Design tokens
tokens = {
    "spacing": [4, 8, 12, 16, 24, 32],
    "borderRadius": [4, 8, 12, 16, 24],
    "shadows": ["sm", "md", "lg"]
}
